If not mounted then try to mount rather than just complaining that the user should do it.
Signed-off-by: David Greaves <david@dgreaves.com>

diff --git a/mer-sdk-chroot b/mer-sdk-chroot
--- a/mer-sdk-chroot
+++ b/mer-sdk-chroot
@@ -307,25 +307,26 @@ cleanup () {
 ################################################################
 # utility
 ensure_mounted() {
-    [[ -e ${sdkroot}/.sdkoptions ]] || {
+    if ! grep " $sdkroot " /proc/mounts > /dev/null; then
 	cat <<EOF
-This SDK ( ${sdkroot} ) does not appear to be mounted.
-Have you run $0 mount?
-
-(Check /proc/self/mounts to be sure.)
+This SDK ( ${sdkroot} ) does not appear to be mounted yet - attempting mount:
 EOF
-	exit 1;
-    }
+	if $0 mount; then
+	    return
+	else
+	    echo "Mounting failed, not entering SDK"
+	    exit 1;
+	fi
+    fi
 }
 ensure_not_mounted() {
-    [[ -e ${sdkroot}/.sdkoptions ]] && {
+    if grep " $sdkroot " /proc/mounts > /dev/null; then
 	cat <<EOF
 This SDK ( ${sdkroot} ) is already mounted.
 If you are sure this is not an error and /proc/self/mounts has no mountpoints under it then remove ${sdkroot}/.sdkoptions and try again.
 EOF
 	exit 1;
-    }
-
+    fi
 }
 stash_mount_options() {
     cat <<EOF > ${sdkroot}/.sdkoptions
