[mb2] Store all %prep changes in VCS. JB#58944

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -518,11 +518,17 @@ COMMANDS
     prepare
         Run rpmbuild. Execute just the %prep section of the RPM SPEC file.
 
-        If the %prep section applies any patches and a supported version
-        control system (VCS) is used to manage the source tree, patches are
-        applied with the help of the VCS unless the '--no-vcs-apply' global
-        option is used. Speaking the language of Git, the only supported VCS at
-        the moment, a new commit will be created for each applied patch.
+        When a supported version control system (VCS) is used to manage the
+        source tree, any changes introduced by executing the %prep section
+        will be applied with the help of the VCS in order to keep your own
+        changes safe and clearly separated.
+
+        Speaking the language of Git, the only supported VCS at the moment,
+        new commits will be created - one for each applied patch and a final
+        one for changes introduced other way than by applying patches.
+
+        The above described behavior may be suppressed by the '--no-vcs-apply'
+        global option.
 
     apply [-R]
         Apply all patches defined in the RPM SPEC file to the source tree.
@@ -2766,6 +2772,70 @@ switch_to_snapshot() {
     fi
 }
 
+# Intentionally uses git directly (does not use git_). It is only meant to be
+# used from %prep and that is not allowed to run on shadow build side.
+init_commit_prep_changes_hook() {
+    local hook=$1
+
+    # Use git from host
+    git() { SBOX_DISABLE_MAPPING=1 /usr/bin/git "$@"; }
+
+    commit_all() {
+        if [[ $(git status --untracked-files=no --porcelain --ignore-submodules) ]]; then
+            # No way to auto add everything except submodule changes, so add
+            # everything first, then reset submodules
+            git add -u
+            local submodule=
+            for submodule in $(git submodule foreach --quiet 'printf "%s\n" "$displaypath"'); do
+                git reset --quiet -- "$submodule"
+            done
+
+            local message="${PREPARE_LEADER}(%prep)"
+            message+=$'\n\n'"These changes were introduced by other means than applying patches."
+
+            # Use --allow-empty just to be sure.
+            if ! git_commit_brief --allow-empty --message "$message"; then
+                echo "$self: Failed to git-commit changes done by the %prep section" >&2
+                return 1
+            fi
+        fi
+    }
+
+    main() {
+        local self=${0#$PWD/}
+
+        export GIT_AUTHOR_NAME=$FAKE_GIT_AUTHOR
+        export GIT_AUTHOR_EMAIL=$FAKE_GIT_EMAIL
+        export GIT_COMMITTER_NAME=$FAKE_GIT_AUTHOR
+        export GIT_COMMITTER_EMAIL=$FAKE_GIT_EMAIL
+
+        local ec=0
+
+        commit_all || ec=1
+        local submodule=
+        for submodule in $(git submodule foreach --quiet --recursive 'printf "%s\n" "$displaypath"'); do
+            (cd "$submodule" && commit_all) || ec=1
+        done
+
+        return $ec
+    }
+
+    init_wrappers_dir
+    cat <<END >"$hook"
+FAKE_GIT_AUTHOR=$(quote "$FAKE_GIT_AUTHOR")
+FAKE_GIT_EMAIL=$(quote "$FAKE_GIT_EMAIL")
+PREPARE_LEADER=$(quote "$PREPARE_LEADER")
+
+$(declare -f git)
+$(declare -f git_commit_brief)
+$(declare -f commit_all)
+$(declare -f main)
+
+main
+END
+    chmod +x "$hook"
+}
+
 sign_rpms__prepare() {
     if ! [[ -x $SDK_RPMSIGN ]]; then 
         sign_rpms_native__prepare
@@ -3091,6 +3161,8 @@ run_build__process_args() {
 }
 
 run_build() {
+    local extra_args=()
+
     maybe_increment_build_number "$OPT_SPEC"
 
     flatten_spec "$OPT_SPEC" >"$TMP_SPEC"
@@ -3124,7 +3196,12 @@ run_build() {
     fi
 
     if [[ ! $BUILD_NOPREP_ARGS && ! $OPT_NO_VCS_APPLY ]] && inside_git_worktree; then
+        if [[ $(git_ status --porcelain --untracked-files=no) ]]; then
+            fatal "Refusing to prepare dirty work tree - commit or reset your changes first."
+        fi
         init_patch_wrapper $WRAPPERSDIR/patch
+        init_commit_prep_changes_hook "$WRAPPERSDIR/$WE-commit-prep-changes"
+        extra_args+=(--define "__spec_prep_post $WE-commit-prep-changes; %{___build_post}")
     fi
 
     (
@@ -3141,6 +3218,7 @@ run_build() {
             "${EXTENDED_PRE_INSTALL_LOCK_ARGS[@]}" \
             --buildroot="$buildroot" \
             "${BUILD_NOPREP_ARGS[@]}" "${BUILD_NOCHECK_ARGS[@]}" \
+            "${extra_args[@]}" \
             -bb \
             "$TMP_SPEC" \
             "${BUILD_EXTRA_ARGS[@]}"
@@ -3162,6 +3240,8 @@ run_build() {
 }
 
 run_prepare() {
+    local extra_args=()
+
     ! is_shadow_build || fatal "The 'prepare' command must be used on the source tree."
 
     maybe_increment_build_number "$OPT_SPEC"
@@ -3178,7 +3258,12 @@ run_prepare() {
     build_tgt=${build_tgt%-gnueabi}
 
     if [[ ! $OPT_NO_VCS_APPLY ]] && inside_git_worktree; then
+        if [[ $(git_ status --porcelain --untracked-files=no) ]]; then
+            fatal "Refusing to prepare dirty work tree - commit or reset your changes first."
+        fi
         init_patch_wrapper $WRAPPERSDIR/patch
+        init_commit_prep_changes_hook "$WRAPPERSDIR/$WE-commit-prep-changes"
+        extra_args+=(--define "__spec_prep_post $WE-commit-prep-changes; %{___build_post}")
     fi
 
     (
@@ -3189,6 +3274,7 @@ run_prepare() {
             --define "_sourcedir $OPT_PKGDIR" \
             --define "_buildhost $(get_hostname)" \
             --define "__patch patch" \
+            "${extra_args[@]}" \
             -bp --short-circuit \
             "$TMP_SPEC"
     )
