[mb2] Add '--manual' and '--all' options to 'deploy'. JB#45576

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -90,13 +90,14 @@ Limitations related to shadow builds:
 
 SHARED OUTPUT DIRECTORY
 
-To make deployment easier it is possible to use a shared output directory
-specified with the '--output-dir' option or more conveniently with the
-combination of '--output-prefix' and '--task' options.  Consider enabling
-'--output-prefix' and '--task' by default by creating an alias in your
-'~/.mersdk.profile' to get build results grouped by the tasks they are
-related to.  By default the task will be determined based on the current Git
-branch - check '--task' for more details:
+With shared output directory, it is possible to deploy all required packages
+built from different sources more conveniently. This can be achieved with the
+'--output-dir' option or even better with the combination of '--output-prefix'
+and '--task' options.  Consider enabling '--output-prefix' and '--task' by
+default by creating an alias in your '~/.mersdk.profile' to get build results
+grouped by the tasks they are related to.  By default, the task will be
+determined based on the current Git branch - check the '--task' option
+description for more details:
 
     alias mb2='mb2 --output-prefix ~/RPMS --task'
 
@@ -106,12 +107,16 @@ branch - check '--task' for more details:
     cd ../packageB
     git checkout -b bugXXXXX
     mb2 -t target build
-    rsync -av ~/RPMS/bugXXXXX-target/ device:RPMS \\
-        && ssh device zypper -p RPMS -v dup
+
+    ls -1 ~/RPMS/bugXXXXX-my-target/
+    mb2 -t target -d device deploy --manual --all \\
+        && ssh device sudo zypper -p RPMS -v dup
 
 With these options the output directory is also searched for build-time
 dependencies by default, so if packageB requires packageA at build time, you
 do not need to install packageA manually to the build target.
+
+Note that it can be usefull to also pass '--from ~plus-repo-1' to 'zypper dup'.
 
 
 CLEAN BUILDS
@@ -287,10 +292,18 @@ COMMANDS
         effect is cumulative and persists until overriden with later name
         prefixed with the opposite operator.
 
-    deploy {--pkcon|--rsync|--sdk|--zypper} [--debug] [--] [[+|-]<pattern>...]
-        Deploy build results to a device. This implies also the "make-install"
-        step and except for the --rsync method it will include also the
-        "package" step.
+    deploy {--pkcon|--rsync|--sdk|--zypper|--manual} [--all] [--debug]
+           [--] [[+|-]<pattern>...]
+        Deploy build results to a device. Unless mentioned otherwise, this
+        implies also the "make-install" and "package" steps. A common exception
+        is when the '--all' option is used.
+
+        By default, just the build results of the project under current working
+        directory will be deployed. When a shared output directory is used (see
+        '--output-dir' and '--output-prefix'), the option '--all' can be used to
+        require deployment of all packages found under the output directory, no
+        matter of their origin. The '--all' option is not available when the
+        '--rsync' method is used.
 
         Selection of (sub)packages for deployment can be influenced with glob
         <pattern>s, each of which may be preceded with '+' or '-' to opt for
@@ -311,7 +324,8 @@ COMMANDS
         --rsync
             Uses 'rsync' to copy the installed files under '/opt/sdk/<name>'
             without building/installing RPM package(s).  Does not require root
-            access to the device.
+            access to the device.  With this method the "package" step is not
+            implied. Incompatible with '--all'.
 
         --sdk
             Uses the method native to the SDK to install RPM package(s).
@@ -321,6 +335,10 @@ COMMANDS
         --zypper
             Uses 'zypper' to install RPM package(s).  Requires 'zypper'
             installed on the device, requires root access to the device.
+
+        --manual
+            Only transfers the RPM package(s) to the device for manual
+            installation. Uses '~/RPMS' as the target directory on the device.
 
     run [<command> [<args>]]
         Run the given command on the device specified with '--device'.  Can be
@@ -648,10 +666,49 @@ match_multi() {
     [[ (! $inclusion_limited || $included) && ! $excluded ]]
 }
 
-# Find binary rpms under <dir> built from the given <spec>, filtering according to <patterns>
+find_latest_rpms() {
+    local dir=$1 patterns=("${@:2}")
+
+    local latest=$(
+        zypper --plus-repo "$dir/" search --repo ~plus-repo-1 --details \
+            `# drop header` \
+            |sed '1,/^--/d' \
+            `# zypper sorts by version: revert it and keep first for each name` \
+            |tac |sort --stable -t '|' -k 2,2 -u \
+            `# $name $dir/$name-$evr.$arch.rpm` \
+            |awk -F ' *\\| *' -v dir="$dir" '{print $2, dir "/" $2 "-" $4 "." $5 ".rpm"}'
+    )
+
+    [[ $latest ]] || return
+
+    local name= pkg=
+    while read name pkg; do
+        if [[ ! -f "$pkg" ]]; then
+            fatal "Internal error: Package does not exist: '$pkg'"
+        fi
+        if match_multi "$name" "${patterns[@]}"; then
+            printf '%s\n' "$pkg"
+        fi
+    done <<<"$latest"
+}
+
+# Find binary rpms under <dir> built from the given <spec>, filtering according
+# to <patterns>. If '--all' is used (must be the very first option), ignore
+# <spec> and find latest packages no matter of their origin.
 find_rpms()
 {
+    local all=
+    if [[ $1 == --all ]]; then
+        all=1
+        shift
+    fi
+
     local dir=$1 spec=$2 patterns=("${@:3}")
+
+    if [[ $all ]]; then
+        find_latest_rpms "$dir" "${patterns[@]}"
+        return
+    fi
 
     local wanted_source_name= wanted_evr=
     read wanted_source_name wanted_evr < <(rpmspec -q --srpm --queryformat '%{NAME} %{EVR}\n' "$spec")
@@ -1375,12 +1432,15 @@ run_deploy() {
     [[ $device_type ]] || fatal "No device specified"
     [[ -e $STATEDIR/spec ]] || fatal "No previoud build found"
 
-    local method_opt= patterns=('-*-debug@(info|source)')
+    local method_opt= all_opt= patterns=('-*-debug@(info|source)')
     while [[ $# -ne 0 ]]; do
         case $1 in
-            --sdk | --pkcon | --zypper | --rsync )
+            --sdk | --pkcon | --zypper | --rsync | --manual )
                 [[ ! $method_opt ]] || fatal "Cannot combine '$1' and '$method_opt'"
                 method_opt=$1
+                ;;
+            --all )
+                all_opt=$1
                 ;;
             --debug )
                 patterns=
@@ -1398,6 +1458,7 @@ run_deploy() {
         shift
     done
 
+    [[ ! $all_opt || $method_opt != --rsync ]] || fatal "Cannot use '--all' with '--rsync'"
     [[ ${method_opt:-} ]] || fatal "Argument expected"
 
     local retcode=0
@@ -1410,9 +1471,8 @@ run_deploy() {
             else
                 method="pkcon --plain --noninteractive install-local"
             fi
-            run_package
-            [[ $? -ne 0 ]] && return 1
-            rpms=$(find_rpms "$OPT_OUTPUTDIR" "$STATEDIR/spec" "${patterns[@]}")
+            [[ $all_opt ]] || run_package || return
+            rpms=$(find_rpms $all_opt "$OPT_OUTPUTDIR" "$STATEDIR/spec" "${patterns[@]}")
             [[ $rpms ]] || fatal "No package found or none matched the given criteria"
             rsync_as $deviceuser -av ${rpms} $device_ip:/home/$deviceuser/RPMS/
             [[ $? -ne 0 ]] && return 1
@@ -1422,9 +1482,8 @@ run_deploy() {
             ssh_as $deviceuser rm -f ${device_rpms}
             ;;
         --zypper )
-            run_package
-            [[ $? -ne 0 ]] && return 1
-            rpms=$(find_rpms "$OPT_OUTPUTDIR" "$STATEDIR/spec" "${patterns[@]}")
+            [[ $all_opt ]] || run_package || return
+            rpms=$(find_rpms $all_opt "$OPT_OUTPUTDIR" "$STATEDIR/spec" "${patterns[@]}")
             [[ $rpms ]] || fatal "No package found or none matched the given criteria"
             rsync_as root -av ${rpms} $device_ip:/root/RPMS/
             [[ $? -ne 0 ]] && return 1
@@ -1439,6 +1498,14 @@ run_deploy() {
             name=$(get_spec_tag "%{name}")
             rsync_as $deviceuser -av ${buildroot}/. $device_ip:/opt/sdk/$name
             retcode=$?
+            ;;
+        --manual )
+            [[ $all_opt ]] || run_package || return
+            rpms=$(find_rpms $all_opt "$OPT_OUTPUTDIR" "$STATEDIR/spec" "${patterns[@]}")
+            [[ $rpms ]] || fatal "No package found or none matched the given criteria"
+            rsync_as $deviceuser -av ${rpms} $device_ip:/home/$deviceuser/RPMS/
+            [[ $? -ne 0 ]] && return 1
+            retcode=0
             ;;
         *)
             fatal "Internal error: Invalid deployment method: '$1'"
@@ -3653,6 +3720,94 @@ run_tc match_multi "Override exclusion later" foobar doobar "-*bar" "zoo*" "foo*
 run_tc match_multi "Override inclusion later" foobar doobar "*bar" "zoo*" "-doo*"
 run_tc match_multi "Extglob" foobar doobar "foo@(bar|baz)"
 tear_down_ts match_multi
+
+################################################################################
+# Test find_latest_rpms
+
+make_test_package() {
+    local name=$1 version=$2 release=$3
+
+    # Create a minimal spec file
+    mkdir -p rpm || return
+    cat >rpm/test.spec <<END || return
+Name:       ${name}
+
+# This is to not require meego-rpm-config installed for self-test execution
+%global __os_install_post %{nil}
+
+Summary:    Test
+Version:    ${version}
+Release:    ${release}
+Group:      Qt/Qt
+License:    LICENSE
+URL:        http://example.org/
+Source0:    %{name}-%{version}.tar.bz2
+
+%description
+Test
+
+%build
+
+%install
+mkdir -p %{buildroot}
+touch %{buildroot}/foo
+
+%files
+%defattr(-,root,root,-)
+/foo
+END
+    # Set output-dir explicitly to prevent removal of previously built packages
+    mkdir -p RPMS || return
+    "$SELF" --output-dir RPMS build || return
+}
+
+find_latest_rpms_tc() {
+    sb2_stub_create || return
+
+    make_test_package "test1" "1.2.3" "1" || return
+    make_test_package "test1" "1.2.3+jb12345.20200202202020.deadbeef" "1" || return
+    make_test_package "test1" "1.2.3+jb12345.20200222222222.beefbabe" "1" || return
+    make_test_package "test2" "3.2.1" "1" || return
+    make_test_package "test2" "3.3" "1" || return
+
+    local expected=$(cat <<END
+RPMS/test1-1.2.3+jb12345.20200222222222.beefbabe-1.i486.rpm
+RPMS/test2-3.3-1.i486.rpm
+END
+)
+    local actual=
+    actual=$(set +o nounset; find_latest_rpms "RPMS") || return
+
+    if [[ $actual != "$expected" ]]; then
+        cat <<END
+Test case failed: $TC_NAME
+  ** Expected   ** [[
+$expected
+]]
+  ** Actual     ** [[
+$actual
+]]
+END
+        return 1
+    fi
+
+    return 0
+}
+
+find_latest_rpms_tc_tear_down() {
+    sb2_stub_remove || return
+    rm -f rpm/test.spec || return
+    rmdir rpm || return
+    rm -f RPMS/test1-1.2.3-1.i486.rpm || return
+    rm -f RPMS/test1-1.2.3+jb12345.20200202202020.deadbeef-1.i486.rpm || return
+    rm -f RPMS/test1-1.2.3+jb12345.20200222222222.beefbabe-1.i486.rpm || return
+    rm -f RPMS/test2-3.2.1-1.i486.rpm || return
+    rm -f RPMS/test2-3.3-1.i486.rpm || return
+    ! [[ -d RPMS ]] || rmdir RPMS || return
+    rm -f "$buildroot/foo" || return
+}
+
+run_tc find_latest_rpms "Test find_latest_rpms"
 
 ################################################################################
 
