[mb2] Do not switch to a snapshot if target is not needed. JB#59569

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -5045,25 +5045,21 @@ fi
     || fatal "'$OPT_TARGET' is not a known build target"
 
 OPT_ORIGINAL_TARGET=$OPT_TARGET
-if [[ ! $OPT_NO_SNAPSHOT && ! $MB2_SELF_TEST_RUN ]]; then
+if [[ ! $OPT_NEEDTARGET ]]; then
+    # Just in case we failed to set OPT_NEEDTARGET correctly
+    OPT_TARGET+=--some-garbage-to-prevent-accidental-use
+elif [[ ! $OPT_NO_SNAPSHOT && ! $MB2_SELF_TEST_RUN ]]; then
     reset=soft
     # Only commands that do pull build-requires should reset.
     # The 'build-requires' command resets on its own based on its arguments.
     if [[ $OPT_PULL_BUILD_REQUIRES && $1 = @(prepare|build|qmake|cmake|compiledb)  ]]; then
         reset=outdated
     fi
-
     switch_to_snapshot --reset="$reset" || fatal "Failed to init build target snapshot"
-
 elif [[ $OPT_NO_SNAPSHOT != force && ! $MB2_SELF_TEST_RUN ]]; then
     if [[ $(sdk-manage target list --snapshots-of "$OPT_TARGET") ]]; then
-        if [[ $OPT_NEEDTARGET ]]; then
-            echo >&2 "The '$OPT_TARGET' target has snapshots - refusing to use it directly."
-            exit 1
-        else
-            # Just in case we failed to set OPT_NEEDTARGET correctly
-            OPT_TARGET+=--some-garbage-to-prevent-accidental-use
-        fi
+        echo >&2 "The '$OPT_TARGET' target has snapshots - refusing to use it directly."
+        exit 1
     fi
 fi
 
