mb2: Consolidate build requirements handling

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -1250,6 +1250,22 @@ filter_repo()
 maybe_verify_target_dependencies() {
     [[ $OPT_PULL_BUILD_REQUIRES ]] || return 0
 
+    local opt_refresh= opt_reset=
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --refresh)
+                opt_refresh=1
+                ;;
+            --reset)
+                opt_reset=1
+                ;;
+            *)
+                fatal "Internal error: Unexpected argument to ${BASH_FUNCTION[0]}: '$1'"
+                ;;
+        esac
+        shift
+    done
+
     local arg= extra_args=()
     set -- "${BUILD_EXTRA_ARGS[@]}"
     while [[ $# -gt 0 ]]; do
@@ -1267,6 +1283,17 @@ maybe_verify_target_dependencies() {
         esac
         shift
     done
+
+    if [[ $opt_reset ]]; then
+        if ! sdk-manage target snapshot --reset=force "$OPT_ORIGINAL_TARGET" "$OPT_TARGET"; then
+            fatal "Failed to reset build target snapshot '$OPT_TARGET' to '$OPT_ORIGINAL_TARGET'"
+        fi
+    fi
+
+    if [[ $opt_refresh ]]; then
+        # Refresh repos before installing dependencies
+        sb2_maintain zypper --non-interactive ref
+    fi
 
     local deps=()
     readarray -t deps < <(sb2_build rpmspec --query --buildrequires "${extra_args[@]}" \
@@ -2256,16 +2283,10 @@ run_build_requires__process_args() {
 }
 
 run_build_requires() {
-    if [[ $BUILD_REQUIRES_MODE == reset ]]; then
-        if ! sdk-manage target snapshot --reset=force "$OPT_ORIGINAL_TARGET" "$OPT_TARGET"; then
-            fatal "Failed to reset build target snapshot '$OPT_TARGET' to '$OPT_ORIGINAL_TARGET'"
-        fi
-    fi
-    if [[ ! $BUILD_REQUIRES_NOREFRESH ]]; then
-        # Refresh repos before installing dependencies
-        sb2_maintain zypper --non-interactive ref
-    fi
-    OPT_PULL_BUILD_REQUIRES=1 maybe_verify_target_dependencies
+    local args=()
+    [[ $BUILD_REQUIRES_MODE == reset ]] && args+=(--reset)
+    [[ $BUILD_REQUIRES_NOREFRESH ]] || args+=(--refresh)
+    OPT_PULL_BUILD_REQUIRES=1 maybe_verify_target_dependencies "${args[@]}"
 }
 
 run_apply__process_args() {
