[mb2] Allow to diff/reset build requires without spec. JB#57656

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -2529,11 +2529,31 @@ run_build_requires__process_args() {
         notice "Omitting 'pull' is deprecated. Pass 'pull' explicitly."
         BUILD_REQUIRES_MODE=pull
     fi
+    if [[ $BUILD_REQUIRES_MODE == pull ]]; then
+        OPT_NEEDSPEC=1
+    fi
 }
 
 run_build_requires() {
+    local locked=
+    run_build_requires_cleanup() (
+        trap 'echo cleaning up...' INT TERM HUP
+        [[ $locked ]] && global_lock_release
+    )
+    trap 'run_build_requires_cleanup; trap - RETURN' RETURN
+    trap 'return 1' INT TERM HUP
+
     if [[ $BUILD_REQUIRES_MODE == diff ]]; then
         sdk-manage target package-diff "$OPT_TARGET" "$OPT_ORIGINAL_TARGET"
+        return
+    fi
+
+    if [[ $BUILD_REQUIRES_MODE == reset && ! $OPT_SPEC ]]; then
+        locked=1
+        global_lock_acquire
+        if ! sdk-manage target snapshot --reset=force "$OPT_ORIGINAL_TARGET" "$OPT_TARGET"; then
+            fatal "Failed to reset build target snapshot '$OPT_TARGET' to '$OPT_ORIGINAL_TARGET'"
+        fi
         return
     fi
 
@@ -4023,7 +4043,7 @@ while [[ "$1" ]]; do
             ;;
         # Note that OPT_NEEDSPEC and OPT_NEEDTARGET may be additionaly set later
         # during command options parsing!
-        build | build-requires | cmake | compiledb | deploy | install | installdeps \
+        build | cmake | compiledb | deploy | install | installdeps \
             | make | make-install | package | prep | prepare | qmake | rpm )
             OPT_NEEDSPEC=1
             OPT_NEEDTARGET=1
@@ -4037,7 +4057,7 @@ while [[ "$1" ]]; do
             OPT_NEEDTARGET=1
             break;
             ;;
-        run | ssh | undeploy )
+        run | ssh | undeploy | build-requires )
             break
             ;;
         --version )
