mb2: Add test cases for argument passing

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -668,6 +668,10 @@ get_shared_dir() {
 # this is same as basename $0
 ME=${0/#*\//}
 
+################################################################################
+if [[ $1 != --self-test ]]; then  ###  M A I N  EXECUTION BEGINS HERE  #########
+################################################################################
+
 # option variables
 OPT_SPEC=
 OPT_TARGET=
@@ -892,6 +896,569 @@ case "$1" in
 esac
 
 $cmd "$@"
+
+##############################################################################
+exit; fi ###  S E L F - T E S T  EXECUTION BEGINS HERE #######################
+##############################################################################
+
+set -o nounset
+
+SELF=$(readlink -f "$0")
+
+: ${MB2_SELF_TEST_VERBOSE:=}
+
+temp=$(mktemp -d) || exit
+trap "rm -rf '$temp'" EXIT
+cd "$temp" || exit
+
+mkdir stubs || exit
+STUBS_DIR=$(readlink -f stubs)
+export PATH="$STUBS_DIR:$PATH"
+
+################################################################################
+# Test utils
+
+tc_num=0
+tc_failed_num=0
+
+set_up_ts() {
+    local ts=$1
+    TS_NAME=$2
+    ${ts}_ts_set_up
+    if [[ $? -ne 0 ]]; then
+        fatal "Test suite set-up failed: $ts"
+    fi
+}
+
+tear_down_ts() {
+    local ts=$1
+    ${ts}_ts_tear_down
+    if [[ $? -ne 0 ]]; then
+        fatal "Test suite tear-down failed: $ts"
+    fi
+    TS_NAME=
+}
+
+KNOWN_ISSUES=()
+KNOWN_ISSUE() {
+    KNOWN_ISSUES=(${KNOWN_ISSUES[@]:+"${KNOWN_ISSUES[@]}"} "$1")
+}
+
+run_tc() {
+    local tc=$1
+    TC_NAME=$2
+    local args=("${@:3}")
+
+    let tc_num++
+    echo "*** Executing test case: $TS_NAME - $TC_NAME"
+
+    local known_issue
+    for known_issue in ${KNOWN_ISSUES[@]:+"${KNOWN_ISSUES[@]}"}; do
+        echo "    Known issue: $known_issue"
+    done
+    KNOWN_ISSUES=()
+
+    local stderr=
+    { stderr=$(${tc}_tc "${args[@]}" 3>&1 1>&2 2>&3 3>&-); } 2>&1
+    local rc=$?
+
+    if [[ $rc -ne 0 ]]; then
+        let tc_failed_num++
+    fi
+
+    if [[ $rc -ne 0 || $MB2_SELF_TEST_VERBOSE ]]; then
+        cat <<END
+  ** Stderr     ** [[
+$stderr
+]]
+END
+    fi
+
+    return $rc
+}
+
+arg_pass_stub_create() {
+    while [[ ${1:-} ]]; do
+        local stub=$STUBS_DIR/$1
+        local results=$STUBS_DIR/$1.args
+
+        touch "$results" || return
+        cat >"$stub" <<END || return
+#!/bin/bash
+echo "stub invoked: \$0 \$(printf "%q " "\$@")" >&2
+[[ \$# -ne 0 ]] && printf "%q\\n" "\$@" >"$results"
+exit 0
+END
+        chmod +x "$stub" || return
+        shift
+    done
+}
+
+arg_pass_stub_remove() {
+    while [[ ${1:-} ]]; do
+        local stub=$STUBS_DIR/$1
+        local results=$STUBS_DIR/$1.args
+        rm -f "$stub" || return
+        rm -f "$results" || return
+        shift
+    done
+}
+
+arg_pass_stub_results() {
+    local results=$STUBS_DIR/$1.args
+    cat "$results"
+}
+
+arg_pass_stub_clear() {
+    while [[ ${1:-} ]]; do
+        local results=$STUBS_DIR/$1.args
+        :> "$results" || return
+        shift
+    done
+}
+
+expect_args() {
+    [[ $# -ne 0 ]] && printf "%q\n" "$@" || true
+}
+
+DEFAULT_TARGET=$(. ~/.scratchbox2/config; echo "$DEFAULT_TARGET")
+DEFAULT_JOBS=$(getconf _NPROCESSORS_ONLN)
+
+if [[ -f /etc/mer-sdk-vbox ]]; then
+    DEFAULT_DEVICE="Sailfish OS Emulator"
+else
+    echo "Note: Skipping test cases involving device connection - not inside a Sailfish OS build engine" >&2
+    DEFAULT_DEVICE=
+fi
+
+################################################################################
+# Test sb2 argument passing
+
+sb2_arg_pass_ts_set_up() {
+    arg_pass_stub_create sb2 || return
+
+    # Create an empty spec file
+    mkdir rpm || return
+    cat >rpm/test.spec <<END || return
+# Just say 'define qtc_qmake' to make check_spec_supports_qtc_silent happy
+END
+}
+
+sb2_arg_pass_ts_tear_down() {
+    arg_pass_stub_remove sb2 || return
+    rm -f rpm/test.spec || return
+    rmdir rpm || return
+}
+
+sb2_arg_pass_tc() {
+    local expected=$1
+    local args=("${@:2}")
+
+    arg_pass_stub_clear sb2 || return
+    "$SELF" "${args[@]}" || return
+    local actual_raw= actual= diff=
+    actual_raw=$(arg_pass_stub_results sb2) || return
+    actual=$(sed -e 's,/tmp\.[^/]\+,/@TMPDIR@,' \
+                 -e "s,/home/deploy,/tmp/@TMPDIR@," \
+                 -e 's,/test\.spec\.[^/]\+,/@TEST_SPEC@,' <<<"$actual_raw")
+    if ! diff=$(diff <(cat <<<"$expected") <(cat <<<"$actual")); then
+        cat <<END
+Test case failed: $TC_NAME
+  ** Command    ** $ME $(printf "%q " "${args[@]}")
+  ** Mismatch   ** [[
+$diff
+]]
+  ** Expected   ** [[
+$expected
+]]
+  ** Actual     ** [[
+$actual
+]]
+  ** Actual RAW ** [[
+$actual_raw
+]]
+END
+        return 1
+    fi
+}
+
+set_up_ts sb2_arg_pass "Passing arguments to sb2"
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Does not disable debug by default (ignores --enable-debug)"
+KNOWN_ISSUE "Passes -j without argument"
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc sb2_arg_pass "prep" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --define '_smp_mflags -j' \
+        --define '_rpmdir /tmp/@TMPDIR@/RPMS ' \
+        --define '_sourcedir /tmp/@TMPDIR@/rpm ' \
+        --define '_rpmfilename %%{name}-%%{version}-%%{release}.%%{arch}.rpm ' \
+        --buildroot=/tmp/@TMPDIR@/installroot \
+        --doprep \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    prep "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Does not quote argument to -j"
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc sb2_arg_pass "build" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --define 'debug_package %{nil} ' \
+        --define '_smp_mflags -jbad 1' \
+        --define '_rpmdir /tmp/@TMPDIR@/RPMS ' \
+        --define '_sourcedir /tmp/@TMPDIR@/rpm ' \
+        --define '_rpmfilename %%{name}-%%{version}-%%{release}.%%{arch}.rpm ' \
+        --buildroot=/tmp/@TMPDIR@/installroot \
+        --doprep \
+        --dobuild \
+        --doinstall \
+        --dobinary \
+        --docheck \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    build --doprep -j "bad  1" "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Does not quote argument to -j"
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc sb2_arg_pass "build with debug" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --define '_smp_mflags -jbad 1' \
+        --define '_rpmdir /tmp/@TMPDIR@/RPMS ' \
+        --define '_sourcedir /tmp/@TMPDIR@/rpm ' \
+        --define '_rpmfilename %%{name}-%%{version}-%%{release}.%%{arch}.rpm ' \
+        --buildroot=/tmp/@TMPDIR@/installroot \
+        --doprep \
+        --dobuild \
+        --doinstall \
+        --dobinary \
+        --docheck \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    build --doprep --enable-debug -j "bad  1" "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Passes wrong arguments to qmake"
+run_tc sb2_arg_pass "qmake" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --dobuild \
+        --define 'noecho 1 ' \
+        --define 'qtc_builddir /tmp/@TMPDIR@' \
+        --define 'qtc_make true ignoring make' \
+        --define "qtc_qmake5 %qmake5 'a b' 'c d' 'e' 'f' " \
+        --define "qtc_qmake %qmake 'a b' 'c d' 'e' 'f' " \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    qmake "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Passes wrong arguments to qmake"
+run_tc sb2_arg_pass "make" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --dobuild \
+        --define 'noecho 1 ' \
+        --define 'qtc_builddir /tmp/@TMPDIR@' \
+        --define 'qtc_qmake5 true ignoring qmake' \
+        --define 'qtc_qmake true ignoring qmake' \
+        --define "qtc_make make %{?_smp_mflags} a b c  d e f" \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    make "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc sb2_arg_pass "install" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --define 'noecho 1 ' \
+        --define 'qtc_builddir /tmp/@TMPDIR@' \
+        --define '_sourcedir /tmp/@TMPDIR@/rpm ' \
+        --define '_skip_install_processing 1' \
+        --buildroot='/tmp/@TMPDIR@/installroot' \
+        --doinstall \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    install "a b" "c  d" e f
+
+KNOWN_ISSUE "Adds trailing space to macro definitions"
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc sb2_arg_pass "rpm" \
+    "$(expect_args \
+        -t "$DEFAULT_TARGET" rpmbuild --build-in-place --target= \
+        --define 'noecho 1 ' \
+        --define 'qtc_builddir /tmp/@TMPDIR@' \
+        --define '_rpmdir /tmp/@TMPDIR@/RPMS ' \
+        --define '_sourcedir /tmp/@TMPDIR@/rpm ' \
+        --define '_rpmfilename %%{name}-%%{version}-%%{release}.%%{arch}.rpm ' \
+        --buildroot='/tmp/@TMPDIR@/installroot' \
+        --doinstall \
+        --dobinary \
+        --docheck \
+        /tmp/@TMPDIR@/rpm/@TEST_SPEC@)" \
+    rpm "a b" "c  d" e f
+
+tear_down_ts sb2_arg_pass
+
+################################################################################
+# Test arguments passing to commands invoked by rpmbuild
+
+rpmbuild_arg_pass_sb2_stub() {
+    echo "stub invoked: $0 $(printf "%q " "$@")" >&2
+
+    local args=("$@")
+    bad_args() {
+        echo "stub $0: unexpected arguments: $(printf "%q " "${args[@]}")" >&2
+    }
+
+    if ! [[ $1 == -t && $3 != -* ]]; then
+        bad_args
+        return 1
+    fi
+
+    shift 2
+
+    case $1 in
+        gcc)
+            case $2 in
+                -dumpmachine)
+                    echo "i486-meego-linux"
+                    ;;
+                *)
+                    bad_args
+                    return 1
+                    ;;
+            esac
+            ;;
+        rpmbuild)
+            local args=("$@")
+            for i in ${!args[*]}; do
+                case ${args[i]} in
+                    --doinstall|--dobinary|--docheck)
+                        echo "stub $0: filtering out '${args[i]}' argument to rpmbuild" >&2
+                        unset args[i]
+                        ;;
+                esac
+            done
+            # rpmbuild writes some progress messages to stdout
+            exec "${args[@]}" >&2
+            ;;
+        rpmspec)
+            exec "$@"
+            ;;
+        *)
+            bad_args
+            return 1
+            ;;
+    esac
+}
+
+rpmbuild_arg_pass_ts_set_up() {
+    RPMBUILD_STUBS=(qmake make)
+    arg_pass_stub_create "${RPMBUILD_STUBS[@]}"
+
+    # Create an sb2 stub
+    cat >"$STUBS_DIR/sb2" <<END || return
+#!/bin/bash
+$(declare -f rpmbuild_arg_pass_sb2_stub)
+rpmbuild_arg_pass_sb2_stub "\$@"
+END
+    chmod +x "$STUBS_DIR/sb2" || return
+
+    # Create a minimal spec file
+    mkdir rpm || return
+    cat >rpm/test.spec <<END || return
+Name:       test
+
+# These would normally come from the environment
+%{!?qmake:%define qmake qmake}
+%{!?qmake5:%define qmake5 qmake}
+
+%{!?qtc_qmake:%define qtc_qmake %qmake}
+%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
+%{!?qtc_make:%define qtc_make make}
+%{?qtc_builddir:%define _builddir %qtc_builddir}
+Summary:    Test
+Version:    0.1
+Release:    1
+Group:      Qt/Qt
+License:    LICENSE
+URL:        http://example.org/
+Source0:    %{name}-%{version}.tar.bz2
+
+%description
+Test
+
+%prep
+%setup -q -n %{name}-%{version}
+
+%build
+%qtc_qmake5 
+%qtc_make %{?_smp_mflags}
+
+%install
+mkdir -p %{buildroot}
+
+%files
+%defattr(-,root,root,-)
+END
+}
+
+rpmbuild_arg_pass_ts_tear_down() {
+    arg_pass_stub_remove "${RPMBUILD_STUBS[@]}" || return
+    rm -f "$STUBS_DIR/sb2" || return
+    rm -f rpm/test.spec || return
+    rmdir rpm || return
+}
+
+rpmbuild_arg_pass_tc() {
+    local all_expected=("${@:1:${#RPMBUILD_STUBS[*]}}")
+    local args=("${@:1+${#RPMBUILD_STUBS[*]}}")
+
+    local rc=0
+
+    arg_pass_stub_clear "${RPMBUILD_STUBS[@]}"
+    "$SELF" "${args[@]}" || return
+    local i=
+    for ((i=0; i<${#RPMBUILD_STUBS[@]}; i++)); do
+        local stub= expected= actual= diff=
+        stub=${RPMBUILD_STUBS[i]}
+        expected=${all_expected[i]}
+        actual=$(arg_pass_stub_results "$stub") || return
+        if ! diff=$(diff <(cat <<<"$expected") <(cat <<<"$actual")); then
+            rc=1
+            cat <<END
+Test case failed: $TC_NAME/$i
+  ** Command    ** $ME $(printf "%q " "${args[@]}")
+  ** Failed for ** $stub
+  ** Mismatch   ** [[
+$diff
+]]
+  ** Expected   ** [[
+$expected
+]]
+  ** Actual     ** [[
+$actual
+]]
+END
+        fi
+    done
+
+    return $rc
+}
+
+set_up_ts rpmbuild_arg_pass "Passing arguments to commands invoked by rpmbuild"
+
+KNOWN_ISSUE "Silently ignores extra arguments"
+run_tc rpmbuild_arg_pass "build" \
+    "$(expect_args )" \
+    "$(expect_args -j"$DEFAULT_JOBS")" \
+    build "a b" "c  d" e f
+
+KNOWN_ISSUE "Passes wrong arguments to qmake"
+run_tc rpmbuild_arg_pass "qmake" \
+    "$(expect_args "a b" "c d" e f)" \
+    "$(expect_args )" \
+    qmake "a b" "c  d" e f
+
+KNOWN_ISSUE "Passes wrong arguments to make"
+KNOWN_ISSUE "Passes extra -j to make"
+if [[ $DEFAULT_JOBS -ne 1 ]]; then
+    run_tc rpmbuild_arg_pass "make" \
+        "$(expect_args )" \
+        "$(expect_args -j"$DEFAULT_JOBS" a b c d e f -j"$DEFAULT_JOBS")" \
+        make "a b" "c  d" e f
+else
+    run_tc rpmbuild_arg_pass "make" \
+        "$(expect_args )" \
+        "$(expect_args a b c d e f)" \
+        make "a b" "c  d" e f
+fi
+
+tear_down_ts rpmbuild_arg_pass
+
+################################################################################
+# Test arguments passing to commands invoked using run|ssh subcommand
+
+ssh_arg_pass_ts_set_up() {
+    :
+}
+
+ssh_arg_pass_ts_tear_down() {
+    :
+}
+
+ssh_arg_pass_tc() {
+    local expected=$1
+    local args=("${@:2}")
+
+    local actual= diff=
+    actual=$("$SELF" "${args[@]}")
+    if ! diff=$(diff <(cat <<<"$expected") <(cat <<<"$actual")); then
+        cat <<END
+Test case failed: $TC_NAME
+  ** Command    ** $ME $(quote "${args[@]}")
+  ** Mismatch   ** [[
+$diff
+]]
+  ** Expected   ** [[
+$expected
+]]
+  ** Actual     ** [[
+$actual
+]]
+END
+        return 1
+    fi
+}
+
+set_up_ts ssh_arg_pass "Passing arguments using run|ssh subcommand"
+
+KNOWN_ISSUE "Unable to pass argument with space"
+run_tc ssh_arg_pass "local - just spaces" \
+    'abcdef' \
+    run printf '%q ' 'a b' 'c  d' e f
+
+KNOWN_ISSUE "Unable to pass argument with space"
+KNOWN_ISSUE "Unable to pass argument with newline - interpreted as multiple commands"
+run_tc ssh_arg_pass "local - spaces and newlines" \
+    "''b c d e f" \
+    run printf '%q'$'\n' 'echo b' 'c  d' e f
+
+KNOWN_ISSUE "Unable to pass argument with space"
+KNOWN_ISSUE "Unable to pass argument with backslashes - valid escape sequences are substituted"
+run_tc ssh_arg_pass "local - spaces and backslashes" \
+    'a\ bncndnenfn' \
+    run printf '%q\n' 'a\ b' 'c  d' e f
+
+if [[ $DEFAULT_DEVICE ]]; then
+    KNOWN_ISSUE "Unable to pass argument with space"
+    run_tc ssh_arg_pass "remote - just spaces" \
+        'abcdef' \
+        --device "$DEFAULT_DEVICE" run printf '%q ' 'a b' 'c  d' e f
+
+    KNOWN_ISSUE "Unable to pass argument with space"
+    KNOWN_ISSUE "Unable to pass argument with newline - interpreted as multiple commands"
+    run_tc ssh_arg_pass "remote - spaces and newlines" \
+        "''b c d e f" \
+        --device "$DEFAULT_DEVICE" run printf '%q'$'\n' 'echo b' 'c  d' e f
+
+    KNOWN_ISSUE "Unable to pass argument with space"
+    KNOWN_ISSUE "Unable to pass argument with backslashes - valid escape sequences are substituted"
+    run_tc ssh_arg_pass "remote - spaces and backslashes" \
+        'a\ bncndnenfn' \
+        --device "$DEFAULT_DEVICE" run printf '%q\n' 'a\ b' 'c  d' e f
+fi
+
+tear_down_ts ssh_arg_pass
+
+################################################################################
+
+if [[ $tc_failed_num -eq 0 ]]; then
+    echo "*** All $tc_num tests passed"
+else
+    echo "*** $tc_failed_num out of $tc_num failed"
+fi
 
 # For Emacs:
 # Local Variables:
