[mb2] Allow to achieve clean builds conveniently. Contribute to JB#41701

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -107,6 +107,36 @@ dependencies by default, so if packageB requires packageA at build time, you
 do not need to install packageA manually to the build target.
 
 
+CLEAN BUILDS
+
+It is possible to avoid polluting build targets with build time dependencies
+of a particular package by using the '--snapshot' option. With this option the
+build target is not used directly. Instead a snapshot is taken and the build
+is done using the snapshot of the build target. See '--snapshot' for details
+on how the snapshot is chosen.
+
+The snapshot will be reset automatically whenever the original build target is
+updated, so if e.g. a locally built package is needed as a build-time
+dependency, instead of installing it manually you should rely on the above
+mentioned fact that with custom output directory the '--search-output-dir'
+option is implied, and combine the '--snapshot' option with the
+'--output-prefix' option.
+
+For similar reasons, when mb2 fails to install build-time dependencies due to
+errors like "file not found on the server", .i.e., because the local
+repository cache got outdated, it is the original target that should be
+updated, not the snapshot.
+
+Consider enabling '--snapshot' by default as well:
+
+    alias mb2='mb2 --output-prefix ~/RPMS --snapshot'
+
+In order to ensure targets are not polluted by running mb2 without
+'--snapshot' unintentionally, mb2 requires to use '--no-snapshot' explicitly
+once at least one snapshot exists for a target.  Existing snapshots can be
+listed and removed using 'sdk-assistant'.
+
+
 MAINTAINING CHANGELOGS
 
 If a file exists with '.changes' extension, otherwise matching the
@@ -116,9 +146,16 @@ found instead, this file will be executed and its output treated as
 the actual changelog.
 
 COMMANDS
-    installdeps
+    installdeps [--[no-]refresh] [--reset]
         Install the missing build-time dependencies as is done implicitly by
         the "prep", "build" and "qmake" commands but refresh the package cache
+        first, unless '--no-refresh' is active. When the global '--snapshot'
+        option is used, '--no-refresh' is implied.  This can be overriden with
+        '--refresh' - do not use unless you know what you are doing. If
+        refresh is needed, refresh (and update) the original target instead.
+        The '--reset' option can only be used together with the '--snapshot'
+        global option, with the effect of reseting the target snapshot
+        forcefully to the (possibly updated) state of the original target
         first.
         Compatible global options: -s -t
 
@@ -207,12 +244,30 @@ GLOBAL OPTIONS
     -s, --specfile <file>
         Specify the .spec file
 
+    -S, --snapshot[=<suffix>]
+        Avoid installing build-time dependencies to the sb2 target - use a
+        snapshot of that target instead. The snapshot name will be determined
+        by combining the original target name with the given <suffix>. Any
+        occurence of '%{task}' within the <suffix> will be substituted with
+        the name specified with the '--task' option or with an empty string if
+        the '--task' option is not used. When no suffix was specified or when
+        the substitution yields an empty string, a temporary snapshot will be
+        used (these have ".mb2." followed by random character sequence in
+        their names).  Snapshot state is preserved across mb2 invocations
+        unless the original target was updated meanwhile or it is a temporary
+        snapshot that was previously used with different build tree, in which
+        cases the snapshot will be reset. Snapshot can be reset forcefully
+        using the 'installdeps' command with its '--reset' option.
+
+    --no-snapshot
+        Force mb2 to directly use a target for which snapshots exist.
+
     -f, --shared-folder <dir>
         The folder where QtCreator shares devices.xml and ssh keys this option
         is useful if deploy option is used outside of virtual machine
 
     -T, --task <name>
-        Modifies behavior of the '--output-prefix' option.
+        Modifies behavior of '--output-prefix' and '--snapshot' options.
 
     -x, --fix-version[=<tag>]
         This option is implied when used inside a Git working tree (use -X to
@@ -238,6 +293,12 @@ GLOBAL OPTIONS
         '.changes.run' extension to instruct $ME to generate changelog with
         'git-change-log <args>' instead.
 
+
+KNOWN ISSUES
+
+Build target snapshot is not reset automatically when the original target is
+changed just by removing packages. Package installation or update is needed to
+trigger the automatic reset.
 EOF
 }
 
@@ -700,9 +761,37 @@ END
     chmod +x "$wrapper"
 }
 
+switch_to_snapshot() {
+    OPT_ORIGINAL_TARGET=$OPT_TARGET
+    OPT_SNAPSHOT_SUFFIX=${OPT_SNAPSHOT_SUFFIX//%{task\}/$OPT_TASK}
+
+    if [[ $OPT_SNAPSHOT_SUFFIX ]]; then
+        OPT_TARGET=$OPT_ORIGINAL_TARGET.$OPT_SNAPSHOT_SUFFIX
+        sdk-manage target snapshot --reset=outdated "$OPT_ORIGINAL_TARGET" "$OPT_TARGET" || return
+    else
+        local lock=$STATEDIR/snapshot.lock
+        mkdir -p "$STATEDIR" || return
+        exec 10> "$lock" || return
+        if ! flock --nonblock 10; then
+            fatal "Failed to flock '$lock'"
+        fi
+        OPT_TARGET=$(sdk-manage target reserve "$OPT_ORIGINAL_TARGET" \
+            "$OPT_ORIGINAL_TARGET.$SNAPSHOT_POOL_SUFFIX" "$lock" "$SNAPSHOT_POOL_SIZE") || return
+    fi
+
+    notice "The '--snapshot' option is active - using the '$OPT_TARGET' snapshot of the target"
+}
+
 run_installdeps() {
-    # Refresh repos before installing dependencies
-    sb2 -t "$OPT_TARGET" -m sdk-install -R zypper --non-interactive ref
+    if [[ $INSTALLDEPS_RESET ]]; then
+        if ! sdk-manage target snapshot --reset=force "$OPT_ORIGINAL_TARGET" "$OPT_SNAPSHOT"; then
+            fatal "Failed to reset snapshot '$OPT_SNAPSHOT' to '$OPT_ORIGINAL_TARGET'"
+        fi
+    fi
+    if [[ ! $INSTALLDEPS_NOREFRESH ]]; then
+        # Refresh repos before installing dependencies
+        sb2 -t "$OPT_TARGET" -m sdk-install -R zypper --non-interactive ref
+    fi
     verify_target_dependencies
 }
 
@@ -1002,6 +1091,10 @@ ME=${0/#*\//}
 # option variables
 OPT_SPEC=
 OPT_TARGET=
+OPT_ORIGINAL_TARGET=
+OPT_SNAPSHOT=
+OPT_SNAPSHOT_SUFFIX=
+OPT_NO_SNAPSHOT=
 OPT_DEVICE=
 OPT_OUTPUTDIR=$(readlink -f ./RPMS)
 OPT_CLEAN_OUTPUTDIR=1
@@ -1023,6 +1116,8 @@ OPT_NO_DEPS=
 deviceuser=nemo
 
 STATEDIR=$PWD/.mb2
+SNAPSHOT_POOL_SUFFIX=mb2.XXX
+SNAPSHOT_POOL_SIZE=5
 
 # Virtualbox environment will install in this hardcoded location
 if inside_build_engine; then
@@ -1159,6 +1254,20 @@ while [[ "$1" ]]; do
         "-s" | "--specfile" ) shift
             OPT_SPEC="$1"; shift
             ;;
+        "-S" | "--snapshot" ) shift
+            OPT_SNAPSHOT=1
+            OPT_SNAPSHOT_SUFFIX=
+            ;;
+        "-S"=* | "--snapshot"=* )
+            OPT_SNAPSHOT=1
+            OPT_SNAPSHOT_SUFFIX=${1#*=}
+            shift
+            ;;
+        "--no-snapshot" ) shift
+            OPT_SNAPSHOT=
+            OPT_SNAPSHOT_SUFFIX=
+            OPT_NO_SNAPSHOT=1
+            ;;
         "-T" | "--task" ) shift
             OPT_TASK="$1"; shift
             ;;
@@ -1249,14 +1358,46 @@ if [[ $OPT_SEARCH_OUTPUTDIR ]]; then
     mkdir -p "$OPT_OUTPUTDIR"
 fi
 
+if [[ $OPT_SNAPSHOT ]]; then
+    switch_to_snapshot || fatal "Failed to init target snapshot"
+elif [[ ! $OPT_NO_SNAPSHOT ]]; then
+    if [[ $(sdk-manage target list --snapshots-of "$OPT_TARGET") ]]; then
+        echo >&2 "The '$OPT_TARGET' target has snapshots."
+        echo >&2 "Pass '--no-snapshot' to confirm you really want to use the target directly."
+        exit 1
+    fi
+fi
+
 if [[ $OPT_FIX_VERSION_HINT && ! $(git_ tag --list "$OPT_FIX_VERSION_HINT") ]]; then
     fatal "'$OPT_FIX_VERSION_HINT' no such Git tag"
 fi
 
 case "$1" in
-    make | install | installdeps | rpm | deploy | prep )
+    make | install | rpm | deploy | prep )
         cmd=run_$1
         shift
+        ;;
+    installdeps )
+        cmd=run_$1; shift
+        if [[ $OPT_SNAPSHOT ]]; then
+            INSTALLDEPS_NOREFRESH=1
+        fi
+        while [[ "$1" ]]; do
+            case "$1" in
+                --refresh) shift
+                    INSTALLDEPS_NOREFRESH= ;;
+                --no-refresh) shift
+                    INSTALLDEPS_NOREFRESH=1 ;;
+                --reset) shift
+                    if [[ ! $OPT_SNAPSHOT ]]; then
+                        fatal "Cannot do 'installdeps --reset' without '--snapshot'"
+                    fi
+                    INSTALLDEPS_RESET=1 ;;
+                *)
+                    short_usage quit
+                    ;;
+            esac
+        done
         ;;
     apply )
         cmd=run_$1; shift
