[mb2] Refresh git index before creating a stash. JB#57205
Even with core.checkStat=minimal, it can fail in some cases.

diff --git a/sdk-setup/src/mb2 b/sdk-setup/src/mb2
--- a/sdk-setup/src/mb2
+++ b/sdk-setup/src/mb2
@@ -1526,8 +1526,9 @@ maybe_fix_package_version() {
     version=${version#*/}   # allow tags to have a prefix to allow vendor marking
     version=${version#v}    # some people like to prefix versions with a v
 
+    # Git stash is known to fail on git index which was updated on host previously
     local stash=
-    if ! stash=$(git_ stash create); then
+    if ! stash=$(git_ update-index --refresh >/dev/null; git_ stash create); then
         fatal "Cannot save state of Git working tree: git-stash failed."
     fi
     local head=${stash:-$(git_ rev-parse HEAD)}
@@ -1537,7 +1538,7 @@ maybe_fix_package_version() {
         describe_if_modified()
         {
             local stash=
-            stash=$(git stash create) || return
+            stash=$(git update-index --refresh >/dev/null; git stash create) || return
             local head=${stash:-$(git rev-parse HEAD)}
             if [[ $head != $sha1 ]]; then
                 local short=$(git rev-list --max-count=1 --abbrev-commit "$head")
