[sdk-assistant] Check for toolchain presence ASAP. Contributes to JB#36781

diff --git a/sdk-setup/src/sdk-assistant b/sdk-setup/src/sdk-assistant
--- a/sdk-setup/src/sdk-assistant
+++ b/sdk-setup/src/sdk-assistant
@@ -171,6 +171,29 @@ if [[ $OPT_CREATE ]]; then
         guess_target_architecture
     fi
 
+    case $OPT_ARCH in
+        arm )
+            TOOLCHAIN="Mer-SB2-armv7hl"
+            ;;
+        i486 )
+            TOOLCHAIN="Mer-SB2-i486"
+            ;;
+        * )
+            fail "internal error - arch is [$OPT_ARCH]"
+            ;;
+    esac
+
+    if [[ -z $(zypper pt -i | grep $TOOLCHAIN) ]]; then
+        cat <<EOF
+FAIL: Toolchain pattern $TOOLCHAIN is not installed.
+Please install it by issuing the following command:
+
+sudo zypper in -t pattern $TOOLCHAIN
+
+EOF
+        exit 1
+    fi
+
     cat <<EOF
 Creating the target [$OPT_TARGET] for arch [$OPT_ARCH]
 Using rootstrap [$OPT_ROOTSTRAP]
@@ -203,29 +226,6 @@ if [[ -z $OPT_YES ]]; then
 fi
 
 if [[ $OPT_CREATE ]]; then
-    case $OPT_ARCH in
-        arm )
-            TOOLCHAIN="Mer-SB2-armv7hl"
-            ;;
-        i486 )
-            TOOLCHAIN="Mer-SB2-i486"
-            ;;
-        * )
-            fail "internal error - arch is [$OPT_ARCH]"
-            ;;
-    esac
-
-    if [[ -z $(zypper pt -i | grep $TOOLCHAIN) ]]; then
-        cat <<EOF
-FAIL: Toolchain pattern $TOOLCHAIN is not installed.
-Please install it by issuing the following command:
-
-sudo zypper in -t pattern $TOOLCHAIN
-
-EOF
-        exit 1
-    fi
-
     _ sdk-manage --use-chroot-as $USER --target --install $OPT_TARGET $TOOLCHAIN $OPT_ROOTSTRAP
     exit $?
 fi
