[sdk-manage] Eliminate --use-chroot-as option
This option is used to

1. detect the chroot-type SDK installation
2. determine SDK user name

Remove the need for this option by

1. detecting the type of SDK installation by checking for
   /etc/mer-sdk-{chroot,vbox}
2. expecting to be invoked by non-root user instead of root and only
   sudo as root for operations that need root authorization.

diff --git a/sdk-setup/src/sdk-manage b/sdk-setup/src/sdk-manage
--- a/sdk-setup/src/sdk-manage
+++ b/sdk-setup/src/sdk-manage
@@ -7,11 +7,6 @@ usage()
 {
     cat <<EOF
     usage (keep the arguments order):
-           $0 --use-chroot-as <name>  - Use the script in MerSDK chroot mode (not default)
-                                        The option has to be the first option given.
-                                        The <name> is the name of the chroot user.
-                                        This option is supposed to be used only from another
-                                        script.
            $0 --toolchain --list
            $0 --toolchain --install <arch>
            $0 --toolchain --remove <arch>
@@ -53,10 +48,16 @@ EOF
     return 0
 }
 
-if [[ $EUID -ne 0 ]]; then
-    exec sudo $0 "$@"
-    echo "$0 must be run as root and sudo failed; exiting"
-    exit 1
+if [[ $EUID -eq 0 ]]; then
+    echo >&2 "WARNING: Invoking $0 as root is deprecated."
+    if [[ -n $SUDO_USER ]]; then
+        exec sudo -i -u $SUDO_USER $0 "$@"
+        echo >&2 "sudo as '$SUDO_USER' failed"
+        exit 1
+    else
+        echo >&2 "Cannot determine Mer SDK user. Invoke $0 as non-root to fix this."
+        exit 1
+    fi
 fi
 
 # From now on, exit if variables not set
@@ -90,7 +91,7 @@ ensure_installable() {
 install_toolchain() {
     pkg=$1
     if ensure_installable $pkg; then
-	zypper --quiet --non-interactive install -t pattern $pkg
+	sudo zypper --quiet --non-interactive install -t pattern $pkg
 	return $?
     else
 	echo "Toolchain $pkg doesn't exist or is already installed- can not install."
@@ -101,7 +102,7 @@ install_toolchain() {
 remove_toolchain() {
     pkg=$1
     if ensure_installed $pkg; then
-	zypper --quiet --no-refresh --non-interactive remove -t pattern $pkg
+	sudo zypper --quiet --no-refresh --non-interactive remove -t pattern $pkg
 	return $?
     else
 	echo "Toolchain $pkg is not installed - can not remove."
@@ -154,7 +155,7 @@ assert_target_and_setup() {
 
 t_zypper() {
     (
-	sudo -i -u $sdk_user bash -c "sb2 -t $target -m sdk-install -R zypper --quiet $*"
+	sb2 -t $target -m sdk-install -R zypper --quiet "$@"
     )
 }
 
@@ -213,10 +214,10 @@ t_register() {
     [[ -z ${1:-} ]] && return 0
 
     tgt=$1
-    domain=$(sudo -i -u $sdk_user bash -c "sb2 -t $tgt sdk-register -d")
+    domain=$(sb2 -t $tgt sdk-register -d)
     if [[ z"$domain" == zjolla ]]; then
 	echo -n "$tgt: "
-	sudo -i -u $sdk_user bash -c "sb2 -t $tgt -m sdk-install -R sdk-register -u $reg_username -p $reg_password"
+	sb2 -t $tgt -m sdk-install -R sdk-register -u $reg_username -p $reg_password
     else
 	echo "$tgt: Register not needed (domain: ${domain:-empty})"
     fi
@@ -235,7 +236,7 @@ check_target_visible() {
 }
 
 get_targets() {
-    echo $(sudo -i -u $sdk_user sb2-config -f 2>&1)
+    echo $(sb2-config -f 2>&1)
 }
 
 assert_target_name_valid() {
@@ -315,8 +316,8 @@ target_uuidgen()
     fi
 
     echo "target_uuidgen: generating a unique id for $mytarget target"
-    sudo -i -u $sdk_user bash -c "sb2 -t $mytarget -m sdk-install -R rm -f /var/lib/dbus/machine-id"
-    sudo -i -u $sdk_user bash -c "sb2 -t $mytarget -m sdk-install -R dbus-uuidgen --ensure"
+    sb2 -t $mytarget -m sdk-install -R rm -f /var/lib/dbus/machine-id
+    sb2 -t $mytarget -m sdk-install -R dbus-uuidgen --ensure
 }
 
 # add the MerSDK hostname to target's /etc/hosts
@@ -330,7 +331,7 @@ amend_target_hosts()
 	return 0
     fi
 
-    sudo -i -u $sdk_user bash -c "sb2 -t $mytarget -m sdk-install -R sed -i 's,\(127.0.0.1.*\),\1 $myhostname,' /etc/hosts"
+    sb2 -t $mytarget -m sdk-install -R sed -i "s,\(127.0.0.1.*\),\1 $myhostname," /etc/hosts
 }
 
 # handler for failed or canceled target installations
@@ -421,16 +422,16 @@ install_target() {
 
     # Virtualbox shared folders don't work too well at the moment
     # Unpack targets to a private area within the VM
-    rm -rf $mer_targets/$target
-    mkdir -p $mer_targets/$target
+    sudo rm -rf $mer_targets/$target
+    sudo mkdir -p $mer_targets/$target
     cd $mer_targets/$target
 
     # only create host_targets dirs if inside the VM
-    [[ ! $OPT_USE_CHROOT ]] && mkdir -p $host_targets/$target
+    [[ $INSIDE_VBOX ]] && mkdir -p $host_targets/$target
 
     echo
     echo "Unpacking target ..."
-    tar xf "$local_file"
+    sudo tar xf "$local_file"
     local tar_retcode=$?
 
     if [[ ! -z $local_file ]]; then
@@ -447,16 +448,16 @@ install_target() {
 	else
 	    echo "Could not unpack target image"
 	fi
-	rm -rf $mer_targets/$target
+	sudo rm -rf $mer_targets/$target
 	return 4
     fi
 
     # reset the cleanup trap
     trap - EXIT
 
-    chown -R $sdk_user:$sdk_user $mer_targets/$target
+    sudo chown -R $(id -u):$(id -g) $mer_targets/$target
 
-    if [[ ! $OPT_USE_CHROOT ]]; then
+    if [[ $INSIDE_VBOX ]]; then
 	synchronise_target $target
 	[ $? -ne 0 ] && echo "Rsync did not exactly run as intended, expect problems."
     fi
@@ -482,14 +483,12 @@ install_target() {
 	    ;;
     esac
 
-    if [[ $OPT_USE_CHROOT ]]; then
-	local id_u=$(sudo -i -u $sdk_user id -u)
-	local id_g=$(sudo -i -u $sdk_user id -g)
-	sudo -i -u $sdk_user bash -c "cd $PWD; grep :$id_u: /etc/passwd >> etc/passwd"
-	sudo -i -u $sdk_user bash -c "cd $PWD; grep :$id_g: /etc/group >> etc/group"
+    if [[ $INSIDE_CHROOT ]]; then
+	getent passwd $(id -u) |sudo tee -a etc/passwd >/dev/null
+	getent group $(id -u) |sudo tee -a etc/group >/dev/null
     fi
 
-    sudo -i -u $sdk_user bash -c "cd $PWD; sb2-init -L \"--sysroot=/\" -C \"--sysroot=/\" $transparency -m sdk-build -n -N $toolsdir $target $compiler"
+    sb2-init -L "--sysroot=/" -C "--sysroot=/" $transparency -m sdk-build -n -N $toolsdir $target $compiler
 
     # make sure the created target gets a unique id
     target_uuidgen $target
@@ -499,9 +498,9 @@ install_target() {
 
     assert_target_and_setup
 
-    if [[ ! $OPT_USE_CHROOT ]]; then
+    if [[ $INSIDE_VBOX ]]; then
 	echo "Notifying Qt Creator of new target"
-	sudo -i -u $sdk_user updateQtCreatorTargets --name $target --target-xml $target_xml
+	updateQtCreatorTargets --name $target --target-xml $target_xml
     fi
 
     echo "Target $target now setup"
@@ -511,8 +510,8 @@ remove_target() {
     target=$1
     if [ -d $sbox2dir/$target ]; then
 	rm -r $sbox2dir/$target
-	rm -rf $mer_targets/$target
-	if [[ ! $OPT_USE_CHROOT ]]; then
+	sudo rm -rf $mer_targets/$target
+	if [[ $INSIDE_VBOX ]]; then
 	    rm -rf $host_targets/$target
 	    echo "Notifying Qt Creator of removed target"
 	fi
@@ -520,10 +519,10 @@ remove_target() {
 	echo "Note: target $target was not seen by sb2"
     fi
 
-    if [[ ! $OPT_USE_CHROOT ]]; then
-       # Notify Qt Creator always when we're in the VM to keep the
-       # target information in sync
-	sudo -i -u $sdk_user updateQtCreatorTargets --delete --name $target --target-xml $target_xml
+    if [[ $INSIDE_VBOX ]]; then
+        # Notify Qt Creator always when we're in the VM to keep the
+        # target information in sync
+        updateQtCreatorTargets --delete --name $target --target-xml $target_xml
     fi
 }
 
@@ -570,7 +569,7 @@ manage_targets() {
 	    target="${1:-}"
 	    assert_target_name_valid "$target"
 	    synchronise_target "$@"
-	    sudo -i -u $sdk_user updateQtCreatorTargets --name $target --target-xml $target_xml
+	    updateQtCreatorTargets --name $target --target-xml $target_xml
 	    ;;
 	--import ) shift
 	    assert_target_name_valid "${1:-}"
@@ -612,12 +611,12 @@ get_sdk_version() {
 }
 
 upgrade_sdk() {
-    zypper --quiet --non-interactive refresh -f
-    zypper --quiet --non-interactive dup
+    sudo zypper --quiet --non-interactive refresh -f
+    sudo zypper --quiet --non-interactive dup
 }
 
 refresh_sdk() {
-    zypper --quiet --non-interactive refresh -f
+    sudo zypper --quiet --non-interactive refresh -f
 }
 
 register_sdk() {
@@ -719,17 +718,19 @@ get_register_credentials() {
 
 ################
 
-OPT_SDK_USER=mersdk
-OPT_USE_CHROOT=
+INSIDE_CHROOT=$([[ -e /etc/mer-sdk-chroot ]] && echo 1)
+INSIDE_VBOX=$([[ -e /etc/mer-sdk-vbox ]] && echo 1)
 
-set_options() {
-    sdk_user=$OPT_SDK_USER
-    mer_targets=/srv/mer/targets
-    host_targets=/host_targets
-    sbox2dir=/home/$sdk_user/.scratchbox2
-    target_xml=${host_targets}/targets.xml
-}
+# exactly one must be true
+if [[ $INSIDE_CHROOT$INSIDE_VBOX != 1 ]]; then
+    echo "Internal error: Failed to determine type of SDK installation"
+    exit 1
+fi
 
+mer_targets=/srv/mer/targets
+host_targets=/host_targets
+sbox2dir=${HOME}/.scratchbox2
+target_xml=${host_targets}/targets.xml
 
 ################################################################
 # Main
@@ -738,19 +739,6 @@ if ! [[ ${1:-} ]]; then
     usage --exit
 fi
 
-# set the default options
-set_options
-
-# check if the first cmd line option is for chroot usage
-case "$1" in
-    --use-chroot-as ) shift
-	OPT_SDK_USER=$1; shift
-	OPT_USE_CHROOT=1
-	set_options
-	;;
-esac
-
-# handle the rest of the command line options
 case "$1" in
     --toolchain ) shift
 	manage_toolchains "$@"
