[sdk-manage] Use tarball metadata to look up tooling. JB#57474
This removes the need to wait for the tarball to unpack in order to
determine the SSU release.

diff --git a/sdk-setup/src/sdk-manage b/sdk-setup/src/sdk-manage
--- a/sdk-setup/src/sdk-manage
+++ b/sdk-setup/src/sdk-manage
@@ -305,6 +305,26 @@ download() {
     succeeded=1
 }
 
+maybe_get_tarball_meta_data() {
+    local file=$1
+    local mime=
+    mime=$(file --brief --mime-type "$file")
+    if [[ $mime == application/x-7z-compressed ]]; then
+        7z x -so "$file" '*.meta'
+    fi
+}
+
+parse_tarball_meta_data() {
+    local meta=$1
+    local key=$2
+
+    local value=
+    value=$(sed -n "s/^$key=//p" <<<"$meta") || return
+    [[ $value ]] || { echo >&2 "Empty or no '$key' in tarball meta data"; return 1; }
+
+    printf '%s\n' "$value"
+}
+
 maybe_decompress_tarball() {
     local file=$1
     local mime=
@@ -312,7 +332,7 @@ maybe_decompress_tarball() {
     if [[ $mime == application/x-tar ]]; then
         cat "$file"
     else
-        7z x -so "$file"
+        7z x -so "$file" '*.tar'
     fi
 }
 
@@ -335,6 +355,15 @@ get_object_ssu_release() {
 
     local release=
     release=$(get_object_ssu_config "$object" release) || return
+
+    printf '%s\n' "$release"
+}
+
+get_object_ssu_release_from_tarball_meta_data() {
+    local meta=$1
+
+    local release=
+    release=$(parse_tarball_meta_data "$meta" release) || return
 
     printf '%s\n' "$release"
 }
@@ -1915,6 +1944,22 @@ find_suitable_tooling_or()
     printf '%s\n' "$tooling"
 }
 
+unpack_target() {
+    local target=$1
+    local tarball=$2
+
+    echo >&2
+    echo >&2 "Unpacking target ..."
+    if ! maybe_decompress_tarball "$tarball" | sudo tar -C "$MER_TARGETS/$target" -x; then
+        if disk_full "$MER_TARGETS"; then
+            echo >&2 "Not enough disk space to unpack target image"
+        else
+            echo >&2 "Could not unpack target image"
+        fi
+        return 1
+    fi
+}
+
 # Download and install a rootfs
 install_target() {
     local skip_toolchain_check= tooling= tooling_url= toolchain= positional_args=()
@@ -2046,21 +2091,23 @@ install_target() {
     sudo rm -rf "$MER_TARGETS/$target" || return
     sudo mkdir -p "$MER_TARGETS/$target" || return
 
-    echo >&2
-    echo >&2 "Unpacking target ..."
-    if ! maybe_decompress_tarball "$local_file" | sudo tar -C "$MER_TARGETS/$target" -x; then
-        if disk_full "$MER_TARGETS"; then
-	    echo >&2 "Not enough disk space to unpack target image"
-	else
-	    echo >&2 "Could not unpack target image"
-	fi
-        return 1
+    local target_unpacked=
+    local target_release=
+
+    local meta=$(maybe_get_tarball_meta_data "$local_file")
+    if [[ $meta ]]; then
+        target_release=$(get_object_ssu_release_from_tarball_meta_data "$meta")
     fi
 
-    local target_release=
-    target_release=$(get_object_ssu_release "target:$target") || return
+    if [[ ! $target_release ]]; then
+        unpack_target "$target" "$local_file" || return
+        target_unpacked=1
+        target_release=$(get_object_ssu_release "target:$target") || return
+    fi
 
     tooling=$(find_suitable_tooling_or "$target_release" "$tooling") || return
+
+    [[ $target_unpacked ]] || unpack_target "$target" "$local_file" || return
 
     local target_arch=
     target_arch=$(get_object_ssu_config "target:$target" arch) || return
