mb2: support a default target if the user has one

diff --git a/src/mb2 b/src/mb2
--- a/src/mb2
+++ b/src/mb2
@@ -224,7 +224,6 @@ while [[ $1 ]]; do
     case "$1" in
         "-t" | "--target") shift
 	    target="$1"; shift
-	    [[ -d ~/.scratchbox2/$target ]] || fatal "'$target' is an invalid sb2 target"
 	    ;;
         "-d" | "--device") shift
 	    device="$1"; shift
@@ -261,8 +260,14 @@ while [[ $1 ]]; do
 done
 
 if [[ ! $target ]]; then
-    fatal "You must specify an sb2 target"
+    if [[ -f ~/.scratchbox2/config ]]; then
+	. ~/.scratchbox2/config
+	target=$DEFAULT_TARGET
+    fi
+    [[ $target ]] || fatal "You must specify an sb2 target or have a default configured"
+   fi
 fi
+[[ -d ~/.scratchbox2/$target ]] || fatal "$target is an invalid sb2 target"
 
 if [[ ! $spec ]]; then
     numspec=$(ls $pkgdir/*spec 2>/dev/null | wc -l)
