Add a --status to --sdk to allow QtC to verify that all is well
Signed-off-by: David Greaves <david.greaves@jollamobile.com>

diff --git a/src/sdk-manage b/src/sdk-manage
--- a/src/sdk-manage
+++ b/src/sdk-manage
@@ -34,6 +34,7 @@ usage()
 
            $0 --sdk --version
            $0 --sdk --upgrade
+           $0 --sdk --status
 
        This is the Mer SDK VM manager
        For information see https://wiki.merproject.org/wiki/Platform_SDK_on_VirtualBox
@@ -442,6 +443,24 @@ upgrade_sdk() {
     sdk-version --latest --go
 }
 
+sdk_status() {
+    systemctl --failed
+    ERR=$?
+    if VBoxControl -nologo sharedfolder list | grep ' home$' > /dev/null 2>&1 ; then
+	echo "'home' shared folder is missing"
+	ERR=1
+    fi
+    if VBoxControl -nologo sharedfolder list | grep ' config$' > /dev/null 2>&1 ; then
+	echo "'config' shared folder is missing"
+	ERR=1
+    fi
+    if VBoxControl -nologo sharedfolder list | grep ' targets$' > /dev/null 2>&1 ; then
+	echo "'targets' shared folder is missing"
+	ERR=1
+    fi
+    exit $ERR
+}
+
 manage_sdk() {
     if ! [[ $1 ]]; then
 	usage --exit
@@ -450,6 +469,9 @@ manage_sdk() {
     case "$1" in
 	--version )
 	    get_sdk_version
+	    ;;
+	--status )
+	    sdk_status
 	    ;;
 	--upgrade ) shift
 	    upgrade_sdk "$@"
