Add an 'ssh' shared folder mounted at /etc/ssh/authorized_keys/ To point sshd at the correct authorized_keys location and to allow for shared_folders limited username/permissions mapping :   sed -i 's/.*StrictModes.*/StrictModes no/' /etc/ssh/sshd_config   sed -i 's^.*AuthorizedKeysFile.*^AuthorizedKeysFile      /etc/ssh/authorized_keys/%u/authorized_keys^' /etc/ssh/sshd_config
Signed-off-by: David Greaves <david.greaves@jollamobile.com>

diff --git a/src/sdk-info b/src/sdk-info
--- a/src/sdk-info
+++ b/src/sdk-info
@@ -53,6 +53,12 @@ else
     echo '  Failed to mount shared folder "home"'
     fail=1
 fi
+if VBoxControl -nologo sharedfolder list | grep ' ssh$' > /dev/null 2>&1 ; then
+    mount -tvboxsf -o"rw,exec,uid=0,gid=0,dev,fmode=555,dmode=555"  ssh /etc/ssh/authorized_keys || fail=1
+else
+    echo '  Failed to mount shared folder "ssh" - ssh will not work, use console login as root'
+    fail=1
+fi
 if VBoxControl -nologo sharedfolder list | grep ' targets$' > /dev/null 2>&1 ; then
     mount -tvboxsf -o"rw,exec,uid=1001,gid=1001,dev,ttl=200"  targets /host_targets || fail=1
 else
