Checking out-of-disk-space condition. Safer failures.

diff --git a/src/sdk-manage b/src/sdk-manage
--- a/src/sdk-manage
+++ b/src/sdk-manage
@@ -133,39 +133,56 @@ install_target() {
 	install_toolchain $toolchain
     fi
 
+    local_file=""
     if [[ $url = file\:\/\/\/* ]]; then
 	local_file=${url//file\:\/\//}
     else
 	echo Downloading target
 	echo "curl $url > /srv/mer/targets/$name.tar.bz2"
-	curl "$url" > /srv/mer/targets/$name.tar.bz2
+	curl "$url" > "/srv/mer/targets/$name.tar.bz2"
 	curl_status=$?
-	if [ \( $curl_status -ne 0 \) -o \( $(stat -c %s /srv/mer/targets/$name.tar.bz2) -lt 10000 \) ]; then #hash check anybody?
+	if [ \( $curl_status -ne 0 \) -o \( $(stat -c %s "/srv/mer/targets/$name.tar.bz2") -lt 10000 \) ]; then #hash check anybody?
 	    echo "Download failed"
 	    return 3
 	fi
     fi
 
     mkdir /fuck_hardlinks/
+    if [ $? -ne 0 ]; then echo "Couldn't create /fuck_hardlinks/ directory. Delete it if it already exists, and make sure this script has right to create it."; return 6; fi
     cd /fuck_hardlinks/
+    if [ $? -ne 0 ]; then echo "Couldn't enter /fuck_hardlinks/ directory. This shouldn't happen :)"; return 7; fi
 
     echo Decompressing target
-    if [ $local_file ]; then
-	tar jxf $local_file
+
+    if [ -n "$local_file" ]; then
+	tar jxf "$local_file"
     else
-	tar jxf /srv/mer/targets/$name.tar.bz2
+	tar jxf "/srv/mer/targets/$name.tar.bz2"
+    fi
+    
+    if [ $? -ne 0 ]; then
+	if [ "$( df --sync / | tr -s ' ' | tail -n 1 | cut -d ' ' -f 4 )" -lt 10000 ]; then
+	    echo "Not enough disk space to unpack target image"
+	else
+	    echo "Couldn't unpack target image"
+	fi
+	rm -rf /fuck_hardlinks/
+	return 4
     fi
 
     echo Relocating target
-    mkdir /srv/mer/targets/$name
-    rsync -a /fuck_hardlinks/ /srv/mer/targets/$name/
-    chown -R mersdk /srv/mer/targets/$name
+    mkdir "/srv/mer/targets/$name"
+    if [ $? -ne 0 ]; then  rm -rf /fuck_hardlinks/; echo "Couldn't create target directory, aborting."; return 5; fi
+    rsync -a /fuck_hardlinks/ "/srv/mer/targets/$name/"
+    if [ $? -ne 0 ]; then  echo "Rsync didn't exactly run as intended, expect problems."; fi
+    chown -R mersdk "/srv/mer/targets/$name"
+    if [ $? -ne 0 ]; then  echo "Chown of target dir failed, your target may not work properly."; fi
 
     rm -rf /fuck_hardlinks/
     if [ ! $local_file ]; then
-	rm /srv/mer/targets/$name.tar.bz2
+	rm "/srv/mer/targets/$name.tar.bz2"
     fi
-    cd /srv/mer/targets/$name
+    cd "/srv/mer/targets/$name"
 
     transparency=""
     compiler="/usr/bin/gcc"
@@ -176,7 +193,7 @@ install_target() {
 	compiler="/opt/cross/bin/$architecture-meego-linux-gnueabi-gcc"
     fi
 
-    sudo -u mersdk sb2-init -L "--sysroot=/" -C "--sysroot=/" $transparency -m sdk-build -n -N -t / $name $compiler
+    sudo -u mersdk sb2-init -L "--sysroot=/" -C "--sysroot=/" $transparency -m sdk-build -n -N -t / "$name" $compiler
 }
 
 remove_target() {
